In [23]:
import py2neo as pn
import neo4jupyter

# Create a py2neo graph object.
g = pn.Graph("bolt://localhost:7687", auth=("neo4j", "password"), name = 'neo4j')

# Query the graph for the nodes and edges you want to plot.
nodes = g.nodes.match("Author", )
edges = g.relationships.match("REPLYED_TO")

In [1]:
import pandas as pd

df_wcc = pd.read_csv('D:\Projects\BIG_DATA_TWITTER_ANALYSIS\Dataset\GraphConnections\\total_connections\wcc.csv')
df_louvain = pd.read_csv('D:\Projects\BIG_DATA_TWITTER_ANALYSIS\Dataset\GraphConnections\\total_connections\louvain.csv')
df_pagerank = pd.read_csv('D:\Projects\BIG_DATA_TWITTER_ANALYSIS\Dataset\CuratedData\CommunityDetection\pagerank.csv')

In [ ]:
neo4jupyter.init_notebook_mode()
# Plot the graph using neo4jupyter.
neo4jupyter.draw(g, {"label_name": "id"})

In [3]:
df_authors = pd.read_csv('D:\Projects\BIG_DATA_TWITTER_ANALYSIS\Dataset\GraphConnections\\total_connections\\authors_l_w.csv')
df_authors

                        Id  louvainId    wccId
0      1538873394828935168    13144.0      0.0
1      1573273309369597952        1.0      1.0
2      1532651180475547650    32309.0      2.0
3      1585334914747990016        3.0      3.0
4       794685723538358272        4.0      4.0
...                    ...        ...      ...
80615           3293315060    50178.0      0.0
80616            984612852    80616.0  80616.0
80617            260833271    80617.0   4966.0
80618  1582678357040316420    25000.0      0.0
80619  1429592940645519362    80619.0  80619.0

[80620 rows x 3 columns]

In [118]:
def get_wcc_id(text):
    try:
        return df_wcc[df_wcc['nodeId'] == text]['propertyValue'].values[0]
    except:
        return 0

In [4]:
def get_pagerank_id(text):
    try:
        return df_pagerank[df_pagerank['nodeId'] == text]['propertyValue'].values[0]
    except:
        return 0

In [7]:
df_authors['pagerank'] = df_authors['Id'].apply(get_pagerank_id)
df_authors

                        Id  louvainId    wccId  pagerank
0      1538873394828935168    13144.0      0.0  0.150000
1      1573273309369597952        1.0      1.0  0.961240
2      1532651180475547650    32309.0      2.0  0.150000
3      1585334914747990016        3.0      3.0  0.961240
4       794685723538358272        4.0      4.0  0.961240
...                    ...        ...      ...       ...
80615           3293315060    50178.0      0.0  0.831037
80616            984612852    80616.0  80616.0  0.961240
80617            260833271    80617.0   4966.0  0.204542
80618  1582678357040316420    25000.0      0.0  0.346150
80619  1429592940645519362    80619.0  80619.0  0.961240

[80620 rows x 4 columns]

In [8]:
df_authors.to_csv('D:\Projects\BIG_DATA_TWITTER_ANALYSIS\Dataset\GraphConnections\\total_connections\\authors_l_w_p.csv', index=False)